name: node_js CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - '**'

jobs:
  tests:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup Nodejs Env
      run: echo "NODE_VER=`cat .nvmrc`" >> $GITHUB_ENV
    - name: Setup Nodejs
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODE_VER }}
    - run: npm install -g npm@${{ matrix.npm }}

    - name: Check for Mismatch
      run: |
            problems=$(npm ls --all --package-lock-only --json | jq '.problems[]?' -r)
            if [[ -n "$problems" ]]; then
              echo "$problems"
              echo
              echo "Mismatch between package.json and package-lock.json. Please regenerate package lock file with 'npm install'."
              exit 1
            fi
    
    - name: Install dependencies
      run: npm ci

    - name: Package lock check
      run: make validate-no-uncommitted-package-lock-changes

    - name: Extract i18n
      run: npm run i18n_extract

    - name: Lint
      run: npm run lint

    - name: Test
      run: npm run test

    - name: Build
      run: npm run build

    - name: Run Allowlist Audit
      run: npm run audit:allowlisted
